### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As discussed by mail, here's a "starter package" for fastlane metadata (binaries not needed). Be welcome to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance on adjusting it to your wishes (e.g. adding a featureGraphic or per-release changelogs). Please note the limits mentioned there (e.g. shortdesc may not be longer than 80 chars, fulldesc 4000 chars, per-release changelogs 500 chars and plain ASCII, etc).

Once merged, I'll configure my updater to pull this along with future releases – so you are in full control of the content, and things like "old icons" should be things of the past :wink:

### CODE REVIEW

**Comment by umer0586** [comment]
@IzzySoft is this fastlane structure similar to what F-Droid uses?

**Comment by IzzySoft** [comment]
Thanks for merging! Please let us know then when the next release is planned, so metadata can be prepared at F-Droid accordingly (I just did that in my repo, so there it's already active and your changes are applied with each release).

**Comment by umer0586** [comment]
New release published

**Comment by umer0586** [comment]
Yes, this app is not available on F-Droid. Right now, I am learning the procedure for submitting the app there.

**Comment by IzzySoft** [comment]
Oh, that's [easy enough](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp). And when it comes to the metadata YAML file, I can provide the "upper half" by copying from my repo, should you want to go straight for the merge request – and as it's "pure Java", easily amend the rest:

`metadata/github.umer0586.yml`:

```yaml
Categories:
  - Connectivity
License: GPL-3.0-only
AuthorName: Umer Farooq
SourceCode: https://github.com/umer0586/SensorServer
IssueTracker: https://github.com/umer0586/SensorServer/issues
Changelog: https://github.com/umer0586/SensorServer/releases

AutoName: Sensor Server

RepoType: git
Repo: https://github.com/umer0586/SensorServer

Builds:
  - versionName: 3.2.0
    versionCode: 20
    commit: v3.2.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 3.2.0
CurrentVersionCode: 20
```

So instead of opening an RFP and waiting for it to be manually processed, you could simply open a merge request – well, [here it is](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13098). Let's see how it goes, pipelines are running now and first lights are turning green :smiley:

**Comment by IzzySoft** [comment]
Well, that was a straight hit – all engines are green :partying_face: And even with bonus points:

```
$ rbtest SensorServer-v3.2.0.apk github.umer0586_20.apk 
RB confirmed.
```

So it builds **reproducible** – fantastico! Let me update that MR. F-Droid then will ship the APK **you** build and sign, so cross-updates are easily possible.

**Comment by IzzySoft** [comment]
First issuebot report showed up: ALL ENGINES GO! :smiley: Marked for review. And as it's a reproducible build, no need to check if it "works as expected". But if you'd have a short test case for us, that could speed up things a bit (e.g. "start the app, do X, then `curl <whatever>`, you should see Z`). That way we can observe that it really only does what it's intended to. No mistrust here, but everyone expects us to make sure – after all, your app has a "dangerous combination" of permissions (location + internet = potential tracking).

**Comment by umer0586** [comment]
Thank you so much for creating a merge request there! 🌟
I was planning to issue a merge request with `metadata/github.umer0586.sensorserver.yml` since I recently updated the app ID to reflect uniqueness. However, I noticed that the metadata file is named `metadata/github.umer0586.yml`. From now on, all my future releases will have the ID `github.umer.0586.sensorserver`. Will there be any issues with this?

**Comment by umer0586** [comment]
Metadata [file](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13098/diffs) mentions following
```yaml
Binaries: https://github.com/umer0586/SensorServer/releases/download/v%v/SensorServer-v%v.apk
```
So this means that APKs I publish here must follow `SensorServer-v%v.apk` naming pattern ?

**Comment by umer0586** [comment]
Okay I'll then a put a note there once I publish a new release with new `applicationId`😢

**Comment by IzzySoft** [comment]
OK, marked the MR "Draft" so it doesn't get merged accidentally. Let me raise 3 questions/assumptions in this context, and a conclusion:

* the next release will have the new `applicationId`
* you want your app to stay in my repo after it appeared at F-Droid.org
* current users shall be forewarned

=> we should update the app description NOW to point to the upcoming change. Then when the new release is due, ideally let's have one APK with the current `applicationId` including a pop-up on next start pointing out the changes and requesting to switch. This APK could be prepared even in advance, and we just release it the same day the "new one" is released. My updater should "handle" that: it will grab the new APK and complain I have no metadata for it – at which point I grab the "switchy" one manually and publish both at the same day in parallel.

That way we can alleviate the problem. What do you say?

**Comment by umer0586** [comment]
> the next release will have the new applicationId

Yes, [v3.2.0](https://github.com/umer0586/SensorServer/releases/tag/v3.2.0) is the current version. Starting from v3.3.0 and onward, there will be a new `applicationid`

> you want your app to stay in my repo after it appeared at F-Droid.org

I would consider keeping the app in your repo after it appeared at F-Droid.org. I always publish APKs on github's release section since I there are people that directly install app by directly downloading APK from there. Github's analytics reports many views for release section.  

> current users shall be forewarned

 I will refrain from providing advance notice to current users regarding the changes.


> ideally let's have one APK with the current applicationId including a pop-up on next start pointing out the changes and requesting to switch. This APK could be prepared even in advance, and we just release it the same day the "new one" is released. 

I appreciate the idea; however, I have already made code changes since the release of v3.2.0.

**Comment by IzzySoft** [comment]
> I appreciate the idea; however, I have already committed code changes since the release of v3.2.0.

And a manual build with the `applicationId` changed would not work? I'm no Android dev, so forgive my ignorance.

**Comment by umer0586** [comment]
Since the release of v3.2.0, I have changed the applicationId 4c4a7600591c3b2af6ed060c8b96b672c30f7516 and updated the namespace. However, [https://apt.izzysoft.de/fdroid/index/apk/github.umer0586](https://apt.izzysoft.de/fdroid/index/apk/github.umer0586) still shows v3.1.0 as the latest version, whereas the actual latest version is v3.2.0, and I am planning to release v3.3.0 today with a new applicationId.

If I release v3.3.0 and include two binaries, v3.2.0 (with a pop-up) and v3.3.0 with the tag v3.3.0, would that cause a reproducible build failure at F-Droid?

**Comment by umer0586** [comment]
Okay,  l'll then publish v3.2.1 with two APKs

- `SensorServer-v3.2.1.apk` with new Id
- `SensorServer-v3.2.1-deprecated.apk` with old id having pop-up

**Comment by IzzySoft** [comment]
Sounds good, thanks! Please let me know when you'll release that, so I can take the appropriate measures here and at F-Droid.org.

**Comment by umer0586** [comment]
Okay

**Comment by umer0586** [comment]
@IzzySoft v3.2.1 published !

**Comment by IzzySoft** [comment]
Switch initiated in my repo, will now update the MR at F-Droid. You forgot to add the changelog for this version (`fastlane/metadata/android/en-US/changelogs/21.txt`), do you want to add that? Then I'd pull it for my repo (for F-Droid it won't be fetched as it's not at the tag, but that's no issue as there it's the first release anyway).

**Comment by umer0586** [comment]
Yes I forgot, but now I have added that

**Comment by IzzySoft** [comment]
Thanks! Updated here. So the switch will go live properly around 6 pm UTC then :smiley:

**Comment by IzzySoft** [comment]
No it no longer builds reproducibly:

```
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/3m.xml and /tmp/tmp.Qx8fNAUlCY/b/res/3m.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/3n.xml and /tmp/tmp.Qx8fNAUlCY/b/res/3n.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/8E.xml and /tmp/tmp.Qx8fNAUlCY/b/res/8E.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/8_.xml and /tmp/tmp.Qx8fNAUlCY/b/res/8_.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/Ah.xml and /tmp/tmp.Qx8fNAUlCY/b/res/Ah.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/C5.xml and /tmp/tmp.Qx8fNAUlCY/b/res/C5.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/cR1.xml and /tmp/tmp.Qx8fNAUlCY/b/res/cR1.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/Cv.xml and /tmp/tmp.Qx8fNAUlCY/b/res/Cv.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/DV.xml and /tmp/tmp.Qx8fNAUlCY/b/res/DV.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/ew.xml and /tmp/tmp.Qx8fNAUlCY/b/res/ew.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/FZ.xml and /tmp/tmp.Qx8fNAUlCY/b/res/FZ.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/hE.xml and /tmp/tmp.Qx8fNAUlCY/b/res/hE.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/J7.xml and /tmp/tmp.Qx8fNAUlCY/b/res/J7.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/j9.xml and /tmp/tmp.Qx8fNAUlCY/b/res/j9.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/jj.xml and /tmp/tmp.Qx8fNAUlCY/b/res/jj.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/Jk.xml and /tmp/tmp.Qx8fNAUlCY/b/res/Jk.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/lA.xml and /tmp/tmp.Qx8fNAUlCY/b/res/lA.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/m8.xml and /tmp/tmp.Qx8fNAUlCY/b/res/m8.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/mX.xml and /tmp/tmp.Qx8fNAUlCY/b/res/mX.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/OR.xml and /tmp/tmp.Qx8fNAUlCY/b/res/OR.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/rE.xml and /tmp/tmp.Qx8fNAUlCY/b/res/rE.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/u9.xml and /tmp/tmp.Qx8fNAUlCY/b/res/u9.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/w2.xml and /tmp/tmp.Qx8fNAUlCY/b/res/w2.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/WF.xml and /tmp/tmp.Qx8fNAUlCY/b/res/WF.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/WG.xml and /tmp/tmp.Qx8fNAUlCY/b/res/WG.xml differ
Only in /tmp/tmp.Qx8fNAUlCY/a/res: wh1.xml
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/wh.xml and /tmp/tmp.Qx8fNAUlCY/b/res/wh.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/xc.xml and /tmp/tmp.Qx8fNAUlCY/b/res/xc.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/res/xd.xml and /tmp/tmp.Qx8fNAUlCY/b/res/xd.xml differ
Binary files /tmp/tmp.Qx8fNAUlCY/a/resources.arsc and /tmp/tmp.Qx8fNAUlCY/b/resources.arsc differ
```

Checking with our [howto](https://gitlab.com/fdroid/wiki/-/wikis/HOWTO:-diff-&-fix-APKs-for-Reproducible-Builds#differing-xml-files-in-res-address-first): Did you really build from the tag, or did you use a different commit? In the latter case: which (and for the future: don't!)?

PS: Can we move further discussions on this to [the corresponding MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13098) – i.e. can you join us there?

**Pull request merged**
